ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 360
    HFOV: 70
    POSITION: [0, 0.88, 0]
    NOISE_MODEL: "GaussianNoiseModel"
    NOISE_MODEL_KWARGS:
      intensity_constant: 0.1

  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 360
    HFOV: 70
    MIN_DEPTH: 0.1
    MAX_DEPTH: 10.0
    POSITION: [0, 0.88, 0]
#    NOISE_MODEL: "RedwoodDepthNoiseModel"

#  ACTION_SPACE_CONFIG: 'pyrobotnoise'  # pyrobotnoise
#  NOISE_MODEL:
#    ROBOT: "LoCoBot"
#    CONTROLLER: 'Proportional'
#    NOISE_MULTIPLIER: 0.5

TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.36
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'HEADING_SENSOR']
  POINTGOAL_SENSOR:
    GOAL_FORMAT: POLAR
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  MEASUREMENTS: ['DISTANCE_TO_GOAL', "SUCCESS", 'SPL', 'TOP_DOWN_MAP', 'COLLISIONS']
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 4096
  SUCCESS:
    SUCCESS_DISTANCE: 0.36

DATASET:
  TYPE: PointNav-v1
  SPLIT: val
  DATA_PATH: data/pointnav_gibson_v2/{split}/{split}.json.gz
  SCENES_DIR: "data/scene_data/"
